export const countries = [
    { code: "ad", en_name: "Andorra", fr_name: "Andorre", flag: "🇦🇩" },
    {
        code: "ae",
        en_name: "United Arab Emirates",
        fr_name: "Émirats Arabes Unis",
        flag: "🇦🇪",
    },
    { code: "af", en_name: "Afghanistan", fr_name: "Afghanistan", flag: "🇦🇫" },
    {
        code: "ag",
        en_name: "Antigua and Barbuda",
        fr_name: "Antigua-et-Barbuda",
        flag: "🇦🇬",
    },
    { code: "ai", en_name: "Anguilla", fr_name: "Anguilla", flag: "🇦🇮" },
    { code: "al", en_name: "Albania", fr_name: "Albanie", flag: "🇦🇱" },
    { code: "am", en_name: "Armenia", fr_name: "Arménie", flag: "🇦🇲" },
    { code: "ao", en_name: "Angola", fr_name: "Angola", flag: "🇦🇴" },
    { code: "ar", en_name: "Argentina", fr_name: "Argentine", flag: "🇦🇷" },
    {
        code: "as",
        en_name: "American Samoa",
        fr_name: "Samoa américaines",
        flag: "🇦🇸",
    },
    { code: "at", en_name: "Austria", fr_name: "Autriche", flag: "🇦🇹" },
    { code: "au", en_name: "Australia", fr_name: "Australie", flag: "🇦🇺" },
    { code: "aw", en_name: "Aruba", fr_name: "Aruba", flag: "🇦🇼" },
    { code: "ax", en_name: "Åland Islands", fr_name: "Îles Åland", flag: "🇦🇽" },
    { code: "az", en_name: "Azerbaijan", fr_name: "Azerbaïdjan", flag: "🇦🇿" },
    {
        code: "ba",
        en_name: "Bosnia and Herzegovina",
        fr_name: "Bosnie-Herzégovine",
        flag: "🇧🇦",
    },
    { code: "bb", en_name: "Barbados", fr_name: "Barbade", flag: "🇧🇧" },
    { code: "bd", en_name: "Bangladesh", fr_name: "Bangladesh", flag: "🇧🇩" },
    { code: "be", en_name: "Belgium", fr_name: "Belgique", flag: "🇧🇪" },
    {
        code: "bf",
        en_name: "Burkina Faso",
        fr_name: "Burkina Faso",
        flag: "🇧🇫",
    },
    { code: "bg", en_name: "Bulgaria", fr_name: "Bulgarie", flag: "🇧🇬" },
    { code: "bh", en_name: "Bahrain", fr_name: "Bahreïn", flag: "🇧🇭" },
    { code: "bi", en_name: "Burundi", fr_name: "Burundi", flag: "🇧🇮" },
    { code: "bj", en_name: "Benin", fr_name: "Bénin", flag: "🇧🇯" },
    {
        code: "bl",
        en_name: "Saint Barthélemy",
        fr_name: "Saint-Barthélemy",
        flag: "🇧🇱",
    },
    {
        code: "bn",
        en_name: "Brunei Darussalam",
        fr_name: "Brunéi Darussalam",
        flag: "🇧🇳",
    },
    { code: "bo", en_name: "Bolivia", fr_name: "Bolivie", flag: "🇧🇴" },
    { code: "bm", en_name: "Bermuda", fr_name: "Bermudes", flag: "🇧🇲" },
    {
        code: "bq",
        en_name: "Bonaire, Sint Eustatius and Saba",
        fr_name: "Bonaire, Saint-Eustache et Saba",
        flag: "🇧🇶",
    },
    { code: "br", en_name: "Brazil", fr_name: "Brésil", flag: "🇧🇷" },
    { code: "bs", en_name: "Bahamas", fr_name: "Bahamas", flag: "🇧🇸" },
    { code: "bt", en_name: "Bhutan", fr_name: "Bhoutan", flag: "🇧🇹" },
    { code: "bv", en_name: "Bouvet Island", fr_name: "Île Bouvet", flag: "🇧🇻" },
    { code: "bw", en_name: "Botswana", fr_name: "Botswana", flag: "🇧🇼" },
    { code: "by", en_name: "Belarus", fr_name: "Biélorussie", flag: "🇧🇾" },
    { code: "bz", en_name: "Belize", fr_name: "Belize", flag: "🇧🇿" },
    { code: "ca", en_name: "Canada", fr_name: "Canada", flag: "🇨🇦" },
    {
        code: "cc",
        en_name: "Cocos (Keeling) Islands",
        fr_name: "Îles Cocos (Keeling)",
        flag: "🇨🇨",
    },
    {
        code: "cd",
        en_name: "Congo (the Democratic Republic of the)",
        fr_name: "Congo (République démocratique du)",
        flag: "🇨🇩",
    },
    {
        code: "cf",
        en_name: "Central African Republic",
        fr_name: "République centrafricaine",
        flag: "🇨🇫",
    },
    { code: "cg", en_name: "Congo", fr_name: "Congo", flag: "🇨🇬" },
    { code: "ch", en_name: "Switzerland", fr_name: "Suisse", flag: "🇨🇭" },
    {
        code: "ci",
        en_name: "Côte d'Ivoire",
        fr_name: "Côte d'Ivoire",
        flag: "🇨🇮",
    },
    { code: "ck", en_name: "Cook Islands", fr_name: "Îles Cook", flag: "🇨🇰" },
    { code: "cl", en_name: "Chile", fr_name: "Chili", flag: "🇨🇱" },
    { code: "cm", en_name: "Cameroon", fr_name: "Cameroun", flag: "🇨🇲" },
    { code: "cn", en_name: "China", fr_name: "Chine", flag: "🇨🇳" },
    { code: "co", en_name: "Colombia", fr_name: "Colombie", flag: "🇨🇴" },
    { code: "cr", en_name: "Costa Rica", fr_name: "Costa Rica", flag: "🇨🇷" },
    { code: "cu", en_name: "Cuba", fr_name: "Cuba", flag: "🇨🇺" },
    { code: "cv", en_name: "Cabo Verde", fr_name: "Cap-Vert", flag: "🇨🇻" },
    { code: "cw", en_name: "Curaçao", fr_name: "Curaçao", flag: "🇨🇼" },
    {
        code: "cx",
        en_name: "Christmas Island",
        fr_name: "Île Christmas",
        flag: "🇨🇽",
    },
    { code: "cy", en_name: "Cyprus", fr_name: "Chypre", flag: "🇨🇾" },
    { code: "cz", en_name: "Czechia", fr_name: "Tchéquie", flag: "🇨🇿" },
    { code: "de", en_name: "Germany", fr_name: "Allemagne", flag: "🇩🇪" },
    { code: "dj", en_name: "Djibouti", fr_name: "Djibouti", flag: "🇩🇯" },
    { code: "dk", en_name: "Denmark", fr_name: "Danemark", flag: "🇩🇰" },
    { code: "dm", en_name: "Dominica", fr_name: "Dominique", flag: "🇩🇲" },
    {
        code: "do",
        en_name: "Dominican Republic",
        fr_name: "République dominicaine",
        flag: "🇩🇴",
    },
    { code: "dz", en_name: "Algeria", fr_name: "Algérie", flag: "🇩🇿" },
    { code: "ec", en_name: "Ecuador", fr_name: "Équateur", flag: "🇪🇨" },
    { code: "eg", en_name: "Egypt", fr_name: "Égypte", flag: "🇪🇬" },
    { code: "ee", en_name: "Estonia", fr_name: "Estonie", flag: "🇪🇪" },
    {
        code: "eh",
        en_name: "Western Sahara",
        fr_name: "Sahara occidental",
        flag: "🇪🇭",
    },
    { code: "er", en_name: "Eritrea", fr_name: "Érythrée", flag: "🇪🇷" },
    { code: "es", en_name: "Spain", fr_name: "Espagne", flag: "🇪🇸" },
    { code: "et", en_name: "Ethiopia", fr_name: "Éthiopie", flag: "🇪🇹" },
    { code: "fi", en_name: "Finland", fr_name: "Finlande", flag: "🇫🇮" },
    { code: "fj", en_name: "Fiji", fr_name: "Fidji", flag: "🇫🇯" },
    {
        code: "fk",
        en_name: "Falkland Islands (Malvinas)",
        fr_name: "Îles Malouines",
        flag: "🇫🇰",
    },
    { code: "fm", en_name: "Micronesia", fr_name: "Micronésie", flag: "🇫🇲" },
    { code: "fo", en_name: "Faroe Islands", fr_name: "Îles Féroé", flag: "🇫🇴" },
    { code: "fr", en_name: "France", fr_name: "France", flag: "🇫🇷" },
    { code: "ga", en_name: "Gabon", fr_name: "Gabon", flag: "🇬🇦" },
    {
        code: "gb",
        en_name: "United Kingdom",
        fr_name: "Royaume-Uni",
        flag: "🇬🇧",
    },
    { code: "ge", en_name: "Georgia", fr_name: "Géorgie", flag: "🇬🇪" },
    { code: "gd", en_name: "Grenada", fr_name: "Grenade", flag: "🇬🇩" },
    {
        code: "gf",
        en_name: "French Guiana",
        fr_name: "Guyane française",
        flag: "🇬🇫",
    },
    { code: "gg", en_name: "Guernsey", fr_name: "Guernesey", flag: "🇬🇬" },
    { code: "gh", en_name: "Ghana", fr_name: "Ghana", flag: "🇬🇭" },
    { code: "gi", en_name: "Gibraltar", fr_name: "Gibraltar", flag: "🇬🇮" },
    { code: "gl", en_name: "Greenland", fr_name: "Groenland", flag: "🇬🇱" },
    { code: "gm", en_name: "Gambia", fr_name: "Gambie", flag: "🇬🇲" },
    { code: "gn", en_name: "Guinea", fr_name: "Guinée", flag: "🇬🇳" },
    { code: "gp", en_name: "Guadeloupe", fr_name: "Guadeloupe", flag: "🇬🇵" },
    {
        code: "gq",
        en_name: "Equatorial Guinea",
        fr_name: "Guinée équatoriale",
        flag: "🇬🇶",
    },
    { code: "gr", en_name: "Greece", fr_name: "Grèce", flag: "🇬🇷" },
    { code: "gt", en_name: "Guatemala", fr_name: "Guatemala", flag: "🇬🇹" },
    { code: "gu", en_name: "Guam", fr_name: "Guam", flag: "🇬🇺" },
    {
        code: "gw",
        en_name: "Guinea-Bissau",
        fr_name: "Guinée-Bissau",
        flag: "🇬🇼",
    },
    { code: "gy", en_name: "Guyana", fr_name: "Guyana", flag: "🇬🇾" },
    { code: "hk", en_name: "Hong Kong", fr_name: "Hong Kong", flag: "🇭🇰" },
    {
        code: "hm",
        en_name: "Heard Island and McDonald Islands",
        fr_name: "Îles Heard-et-MacDonald",
        flag: "🇭🇲",
    },
    { code: "hn", en_name: "Honduras", fr_name: "Honduras", flag: "🇭🇳" },
    { code: "hr", en_name: "Croatia", fr_name: "Croatie", flag: "🇭🇷" },
    { code: "ht", en_name: "Haiti", fr_name: "Haïti", flag: "🇭🇹" },
    { code: "hu", en_name: "Hungary", fr_name: "Hongrie", flag: "🇭🇺" },
    { code: "id", en_name: "Indonesia", fr_name: "Indonésie", flag: "🇮🇩" },
    { code: "ie", en_name: "Ireland", fr_name: "Irlande", flag: "🇮🇪" },
    { code: "il", en_name: "Israel", fr_name: "Israël", flag: "🇮🇱" },
    { code: "im", en_name: "Isle of Man", fr_name: "Île de Man", flag: "🇮🇲" },
    { code: "in", en_name: "India", fr_name: "Inde", flag: "🇮🇳" },
    {
        code: "io",
        en_name: "British Indian Ocean Territory",
        fr_name: "Territoire britannique de l'océan Indien",
        flag: "🇮🇴",
    },
    { code: "iq", en_name: "Iraq", fr_name: "Irak", flag: "🇮🇶" },
    { code: "ir", en_name: "Iran", fr_name: "Iran", flag: "🇮🇷" },
    { code: "is", en_name: "Iceland", fr_name: "Islande", flag: "🇮🇸" },
    { code: "it", en_name: "Italy", fr_name: "Italie", flag: "🇮🇹" },
    { code: "je", en_name: "Jersey", fr_name: "Jersey", flag: "🇯🇪" },
    { code: "jm", en_name: "Jamaica", fr_name: "Jamaïque", flag: "🇯🇲" },
    { code: "jo", en_name: "Jordan", fr_name: "Jordanie", flag: "🇯🇴" },
    { code: "jp", en_name: "Japan", fr_name: "Japon", flag: "🇯🇵" },
    {
        code: "ju",
        en_name: "Juan De Nova Island",
        fr_name: "Île Juan de Nova",
        flag: "🇾🇹",
    },
    { code: "ke", en_name: "Kenya", fr_name: "Kenya", flag: "🇰🇪" },
    { code: "kg", en_name: "Kyrgyzstan", fr_name: "Kirghizistan", flag: "🇰🇬" },
    { code: "kh", en_name: "Cambodia", fr_name: "Cambodge", flag: "🇰🇭" },
    { code: "ki", en_name: "Kiribati", fr_name: "Kiribati", flag: "🇰🇮" },
    { code: "km", en_name: "Comoros", fr_name: "Comores", flag: "🇰🇲" },
    {
        code: "kn",
        en_name: "Saint Kitts and Nevis",
        fr_name: "Saint-Christophe-et-Niévès",
        flag: "🇰🇳",
    },
    {
        code: "kp",
        en_name: "North Korea",
        fr_name: "Corée du Nord",
        flag: "🇰🇵",
    },
    { code: "kr", en_name: "South Korea", fr_name: "Corée du Sud", flag: "🇰🇷" },
    { code: "xk", en_name: "Kosovo", fr_name: "Kosovo", flag: "🇽🇰" },
    { code: "kw", en_name: "Kuwait", fr_name: "Koweït", flag: "🇰🇼" },
    {
        code: "ky",
        en_name: "Cayman Islands",
        fr_name: "Îles Caïmans",
        flag: "🇰🇾",
    },
    { code: "kz", en_name: "Kazakhstan", fr_name: "Kazakhstan", flag: "🇰🇿" },
    { code: "la", en_name: "Laos", fr_name: "Laos", flag: "🇱🇦" },
    { code: "lb", en_name: "Lebanon", fr_name: "Liban", flag: "🇱🇧" },
    { code: "lc", en_name: "Saint Lucia", fr_name: "Sainte-Lucie", flag: "🇱🇨" },
    {
        code: "li",
        en_name: "Liechtenstein",
        fr_name: "Liechtenstein",
        flag: "🇱🇮",
    },
    { code: "lk", en_name: "Sri Lanka", fr_name: "Sri Lanka", flag: "🇱🇰" },
    { code: "lr", en_name: "Liberia", fr_name: "Libéria", flag: "🇱🇷" },
    { code: "ls", en_name: "Lesotho", fr_name: "Lesotho", flag: "🇱🇸" },
    { code: "lt", en_name: "Lithuania", fr_name: "Lituanie", flag: "🇱🇹" },
    { code: "lu", en_name: "Luxembourg", fr_name: "Luxembourg", flag: "🇱🇺" },
    { code: "lv", en_name: "Latvia", fr_name: "Lettonie", flag: "🇱🇻" },
    { code: "ly", en_name: "Libya", fr_name: "Libye", flag: "🇱🇾" },
    { code: "ma", en_name: "Morocco", fr_name: "Maroc", flag: "🇲🇦" },
    { code: "mc", en_name: "Monaco", fr_name: "Monaco", flag: "🇲🇨" },
    { code: "md", en_name: "Moldova", fr_name: "Moldavie", flag: "🇲🇩" },
    { code: "mg", en_name: "Madagascar", fr_name: "Madagascar", flag: "🇲🇬" },
    { code: "me", en_name: "Montenegro", fr_name: "Monténégro", flag: "🇲🇪" },
    {
        code: "mf",
        en_name: "Saint Martin",
        fr_name: "Saint-Martin",
        flag: "🇲🇫",
    },
    {
        code: "mh",
        en_name: "Marshall Islands",
        fr_name: "Îles Marshall",
        flag: "🇲🇭",
    },
    {
        code: "mk",
        en_name: "North Macedonia",
        fr_name: "Macédoine du Nord",
        flag: "🇲🇰",
    },
    { code: "ml", en_name: "Mali", fr_name: "Mali", flag: "🇲🇱" },
    { code: "mo", en_name: "Macau", fr_name: "Macao", flag: "🇲🇴" },
    { code: "mm", en_name: "Myanmar", fr_name: "Myanmar", flag: "🇲🇲" },
    { code: "mn", en_name: "Mongolia", fr_name: "Mongolie", flag: "🇲🇳" },
    {
        code: "mp",
        en_name: "Northern Mariana Islands",
        fr_name: "Îles Mariannes du Nord",
        flag: "🇲🇵",
    },
    { code: "mq", en_name: "Martinique", fr_name: "Martinique", flag: "🇲🇶" },
    { code: "mr", en_name: "Mauritania", fr_name: "Mauritanie", flag: "🇲🇷" },
    { code: "ms", en_name: "Montserrat", fr_name: "Montserrat", flag: "🇲🇸" },
    { code: "mt", en_name: "Malta", fr_name: "Malte", flag: "🇲🇹" },
    { code: "mu", en_name: "Mauritius", fr_name: "Maurice", flag: "🇲🇺" },
    { code: "mv", en_name: "Maldives", fr_name: "Maldives", flag: "🇲🇻" },
    { code: "mw", en_name: "Malawi", fr_name: "Malawi", flag: "🇲🇼" },
    { code: "mx", en_name: "Mexico", fr_name: "Mexique", flag: "🇲🇽" },
    { code: "my", en_name: "Malaysia", fr_name: "Malaisie", flag: "🇲🇾" },
    { code: "mz", en_name: "Mozambique", fr_name: "Mozambique", flag: "🇲🇿" },
    { code: "na", en_name: "Namibia", fr_name: "Namibie", flag: "🇳🇦" },
    {
        code: "nc",
        en_name: "New Caledonia",
        fr_name: "Nouvelle-Calédonie",
        flag: "🇳🇨",
    },
    { code: "ne", en_name: "Niger", fr_name: "Niger", flag: "🇳🇪" },
    {
        code: "nf",
        en_name: "Norfolk Island",
        fr_name: "Île Norfolk",
        flag: "🇳🇫",
    },
    { code: "ng", en_name: "Nigeria", fr_name: "Nigéria", flag: "🇳🇬" },
    { code: "ni", en_name: "Nicaragua", fr_name: "Nicaragua", flag: "🇳🇮" },
    { code: "nl", en_name: "Netherlands", fr_name: "Pays-Bas", flag: "🇳🇱" },
    { code: "no", en_name: "Norway", fr_name: "Norvège", flag: "🇳🇴" },
    { code: "np", en_name: "Nepal", fr_name: "Népal", flag: "🇳🇵" },
    { code: "nr", en_name: "Nauru", fr_name: "Nauru", flag: "🇳🇷" },
    { code: "nu", en_name: "Niue", fr_name: "Niue", flag: "🇳🇺" },
    {
        code: "nz",
        en_name: "New Zealand",
        fr_name: "Nouvelle-Zélande",
        flag: "🇳🇿",
    },
    { code: "om", en_name: "Oman", fr_name: "Oman", flag: "🇴🇲" },
    { code: "pa", en_name: "Panama", fr_name: "Panama", flag: "🇵🇦" },
    { code: "pe", en_name: "Peru", fr_name: "Pérou", flag: "🇵🇪" },
    {
        code: "pf",
        en_name: "French Polynesia",
        fr_name: "Polynésie française",
        flag: "🇵🇫",
    },
    {
        code: "pg",
        en_name: "Papua New Guinea",
        fr_name: "Papouasie-Nouvelle-Guinée",
        flag: "🇵🇬",
    },
    { code: "ph", en_name: "Philippines", fr_name: "Philippines", flag: "🇵🇭" },
    { code: "pk", en_name: "Pakistan", fr_name: "Pakistan", flag: "🇵🇰" },
    { code: "pl", en_name: "Poland", fr_name: "Pologne", flag: "🇵🇱" },
    {
        code: "pm",
        en_name: "Saint Pierre and Miquelon",
        fr_name: "Saint-Pierre-et-Miquelon",
        flag: "🇵🇲",
    },
    {
        code: "pn",
        en_name: "Pitcairn Islands",
        fr_name: "Îles Pitcairn",
        flag: "🇵🇳",
    },
    { code: "pr", en_name: "Puerto Rico", fr_name: "Porto Rico", flag: "🇵🇷" },
    { code: "ps", en_name: "Palestine", fr_name: "Palestine", flag: "🇵🇸" },
    { code: "pt", en_name: "Portugal", fr_name: "Portugal", flag: "🇵🇹" },
    { code: "pw", en_name: "Palau", fr_name: "Palaos", flag: "🇵🇼" },
    { code: "py", en_name: "Paraguay", fr_name: "Paraguay", flag: "🇵🇾" },
    { code: "qa", en_name: "Qatar", fr_name: "Qatar", flag: "🇶🇦" },
    { code: "re", en_name: "Reunion", fr_name: "La Réunion", flag: "🇷🇪" },
    { code: "ro", en_name: "Romania", fr_name: "Roumanie", flag: "🇷🇴" },
    { code: "rs", en_name: "Serbia", fr_name: "Serbie", flag: "🇷🇸" },
    { code: "ru", en_name: "Russia", fr_name: "Russie", flag: "🇷🇺" },
    { code: "rw", en_name: "Rwanda", fr_name: "Rwanda", flag: "🇷🇼" },
    {
        code: "sa",
        en_name: "Saudi Arabia",
        fr_name: "Arabie Saoudite",
        flag: "🇸🇦",
    },
    {
        code: "sb",
        en_name: "Solomon Islands",
        fr_name: "Îles Salomon",
        flag: "🇸🇧",
    },
    { code: "sc", en_name: "Seychelles", fr_name: "Seychelles", flag: "🇸🇨" },
    { code: "sd", en_name: "Sudan", fr_name: "Soudan", flag: "🇸🇩" },
    { code: "se", en_name: "Sweden", fr_name: "Suède", flag: "🇸🇪" },
    { code: "sg", en_name: "Singapore", fr_name: "Singapour", flag: "🇸🇬" },
    {
        code: "sh",
        en_name: "Saint Helena",
        fr_name: "Sainte-Hélène",
        flag: "🇸🇭",
    },
    { code: "si", en_name: "Slovenia", fr_name: "Slovénie", flag: "🇸🇮" },
    {
        code: "sj",
        en_name: "Svalbard and Jan Mayen",
        fr_name: "Svalbard et Jan Mayen",
        flag: "🇸🇯",
    },
    { code: "sk", en_name: "Slovakia", fr_name: "Slovaquie", flag: "🇸🇰" },
    {
        code: "sl",
        en_name: "Sierra Leone",
        fr_name: "Sierra Leone",
        flag: "🇸🇱",
    },
    { code: "sm", en_name: "San Marino", fr_name: "Saint-Marin", flag: "🇸🇲" },
    { code: "sn", en_name: "Senegal", fr_name: "Sénégal", flag: "🇸🇳" },
    { code: "so", en_name: "Somalia", fr_name: "Somalie", flag: "🇸🇴" },
    { code: "sr", en_name: "Suriname", fr_name: "Suriname", flag: "🇸🇷" },
    {
        code: "ss",
        en_name: "South Sudan",
        fr_name: "Soudan du Sud",
        flag: "🇸🇸",
    },
    {
        code: "st",
        en_name: "Sao Tome and Principe",
        fr_name: "Sao Tomé-et-Principe",
        flag: "🇸🇹",
    },
    { code: "sv", en_name: "El Salvador", fr_name: "Salvador", flag: "🇸🇻" },
    {
        code: "sx",
        en_name: "Sint Maarten",
        fr_name: "Saint-Martin",
        flag: "🇸🇽",
    },
    { code: "sy", en_name: "Syria", fr_name: "Syrie", flag: "🇸🇾" },
    { code: "sz", en_name: "Eswatini", fr_name: "Eswatini", flag: "🇸🇿" },
    {
        code: "tc",
        en_name: "Turks and Caicos Islands",
        fr_name: "Îles Turques-et-Caïques",
        flag: "🇹🇨",
    },
    { code: "td", en_name: "Chad", fr_name: "Tchad", flag: "🇹🇩" },
    {
        code: "tf",
        en_name: "French Southern Territories",
        fr_name: "Terres australes françaises",
        flag: "🇹🇫",
    },
    { code: "tg", en_name: "Togo", fr_name: "Togo", flag: "🇹🇬" },
    { code: "th", en_name: "Thailand", fr_name: "Thaïlande", flag: "🇹🇭" },
    { code: "tj", en_name: "Tajikistan", fr_name: "Tadjikistan", flag: "🇹🇯" },
    { code: "tk", en_name: "Tokelau", fr_name: "Tokelau", flag: "🇹🇰" },
    { code: "tl", en_name: "Timor-Leste", fr_name: "Timor-Leste", flag: "🇹🇱" },
    {
        code: "tm",
        en_name: "Turkmenistan",
        fr_name: "Turkménistan",
        flag: "🇹🇲",
    },
    { code: "tn", en_name: "Tunisia", fr_name: "Tunisie", flag: "🇹🇳" },
    { code: "to", en_name: "Tonga", fr_name: "Tonga", flag: "🇹🇴" },
    { code: "tr", en_name: "Turkey", fr_name: "Turquie", flag: "🇹🇷" },
    {
        code: "tt",
        en_name: "Trinidad and Tobago",
        fr_name: "Trinité-et-Tobago",
        flag: "🇹🇹",
    },
    { code: "tv", en_name: "Tuvalu", fr_name: "Tuvalu", flag: "🇹🇻" },
    { code: "tw", en_name: "Taiwan", fr_name: "Taïwan", flag: "🇹🇼" },
    { code: "tz", en_name: "Tanzania", fr_name: "Tanzanie", flag: "🇹🇿" },
    { code: "ua", en_name: "Ukraine", fr_name: "Ukraine", flag: "🇺🇦" },
    { code: "ug", en_name: "Uganda", fr_name: "Ouganda", flag: "🇺🇬" },
    {
        code: "um",
        en_name: "United States Minor Outlying Islands",
        fr_name: "Îles mineures éloignées des États-Unis",
        flag: "🇺🇲",
    },
    { code: "us", en_name: "United States", fr_name: "États-Unis", flag: "🇺🇸" },
    { code: "uy", en_name: "Uruguay", fr_name: "Uruguay", flag: "🇺🇾" },
    { code: "uz", en_name: "Uzbekistan", fr_name: "Ouzbékistan", flag: "🇺🇿" },
    { code: "va", en_name: "Vatican City", fr_name: "Vatican", flag: "🇻🇦" },
    {
        code: "vc",
        en_name: "Saint Vincent and the Grenadines",
        fr_name: "Saint-Vincent-et-les-Grenadines",
        flag: "🇻🇨",
    },
    { code: "ve", en_name: "Venezuela", fr_name: "Venezuela", flag: "🇻🇪" },
    {
        code: "vg",
        en_name: "British Virgin Islands",
        fr_name: "Îles Vierges britanniques",
        flag: "🇻🇬",
    },
    {
        code: "vi",
        en_name: "United States Virgin Islands",
        fr_name: "Îles Vierges des États-Unis",
        flag: "🇻🇮",
    },
    { code: "vn", en_name: "Vietnam", fr_name: "Vietnam", flag: "🇻🇳" },
    { code: "vu", en_name: "Vanuatu", fr_name: "Vanuatu", flag: "🇻🇺" },
    {
        code: "wf",
        en_name: "Wallis and Futuna",
        fr_name: "Wallis-et-Futuna",
        flag: "🇼🇫",
    },
    { code: "ws", en_name: "Samoa", fr_name: "Samoa", flag: "🇼🇸" },
    { code: "ye", en_name: "Yemen", fr_name: "Yémen", flag: "🇾🇪" },
    { code: "yt", en_name: "Mayotte", fr_name: "Mayotte", flag: "🇾🇹" },
    {
        code: "za",
        en_name: "South Africa",
        fr_name: "Afrique du Sud",
        flag: "🇿🇦",
    },
    { code: "zm", en_name: "Zambia", fr_name: "Zambie", flag: "🇿🇲" },
    { code: "zw", en_name: "Zimbabwe", fr_name: "Zimbabwe", flag: "🇿🇼" },
];
